server.port=8081
spring.application.name=product-service
spring.data.mongodb.uri=mongodb://localhost:27017/product-service

# MCP Server Configuration
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=Product-Service-MCP
spring.ai.mcp.server.sse.enabled=true
